### ISSUE TITLE
are you aware of evil-textobj-tree-sitter?

### ISSUE THREAD

**Issue by hammerandtongs** [foxfriday/evil-ts#1]
https://github.com/meain/evil-textobj-tree-sitter

**Comment by foxfriday** [comment]
Thanks for the link. I'll add it to the readme. Is evil-textobj-tree-sitter intended as a stand alone package,  and works directly with the language grammars? Or does it also depend on treesit? Looking at the repo, I understand what it does, I just don't understand how it does it.

**Comment by junghan0611** [comment]
Here. 

https://github.com/meain/evil-textobj-tree-sitter/issues/76

**Comment by foxfriday** [comment]
I took a look at evil-textobj-tree-sitter earlier. As far as I can tell that package is far more sophisticated than mine. Evil-ts lets treesit do all the heavy lifting and just adds some fairly simple lines of code. So it seems to me like the two packages take a very different and probably irreconcilable approach.

**Comment by meain** [comment]
@foxfriday I'm the author of `evil-textobj-tree-sitter`. I think both of our packages are doing mostly similar things, just a bit differently. `evil-textobj-tree-sitter` also relies on `tree-sitter` under the hood although via `elisp-tree-sitter` instead of builtin `treesit`.

The primary difference and the complexity you felt is from the need to implement a few QOL addons on top of navigating by node names. `evil-textobj-tree-sitter` uses [`queries`](https://github.com/meain/evil-textobj-tree-sitter/tree/master/queries) instead of node names. This becomes necessary when you want to target things more specifically like "inside" of a function or to do things like selecting the comma next to an argument when you want to select "around" an argument. It can also mimic the vim behaviour of selecting the closest "thing" if we are not already on something of the type "thing" when using commands like `vaf` or selecting multiple items by passing in a numbered argument. Another reason is the fact that I had a partly implement things like `treesit-end-of-thing` which was not available in `elisp-tree-sitter`. Another reason for the size is that it currently supports more languages out of the box.

That said, your version currently has the advantage that it works with `treesit`. I hope to add support for it soon, but I need a few more features in `treesit` to implement that. It is being tracked in https://github.com/meain/evil-textobj-tree-sitter/issues/76 as @junghan0611 pointed out. If you are interested in collaborating on this, feel free to reach out :D

**Comment by RomeoV** [comment]
Just my 2ct -- I just upgraded to emacs 29 and tried to install the treesit branch of https://github.com/meain/evil-textobj-tree-sitter/issues/76, however couldn't get it to work. Then I installed this package and it worked practically right away, so I'm happy to have it! Perhaps I'll try the other one again once it has completed the merge.

**Comment by meain** [comment]
> tried to install the treesit branch of https://github.com/meain/evil-textobj-tree-sitter/issues/76, however couldn't get it to work

Sorry to hijack he issue, but feel free to open an issue on evil-texobj-tree-sitter repo if you are running into any issues with the treesit branch. It should be pretty much ready to go and I'm planning to merge it in the coming days. Would be useful to iron out any pending issues.
